- hosts: localhost
  become: true
  vars_files:
    - ../roles/instance_creation/vars/aws_creds.yml
    - ../roles/instance_creation/vars/instance_vars.yml

  roles:
    - role: ../roles/instance_creation
