- name: "Configure web server in private instances"
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: "Start web Server"
  service:
    name: httpd
    state: started
    enabled: yes

- name: "Start firewalld"
  service:
    name: firewalld
    state: started
    enabled: yes

- name: "Clone source code from github repository"
  git:
    repo: https://github.com/Vikas-Prince/My-Portfolio.git
    dest: /var/www/html/
    clone: yes
    update: yes

- name: "Open Port for Web Server"
  ansible.posix.firewalld:
    port: 80/tcp
    state: enabled
    permanent: yes
  notify:
    - restart firewalld
