- name: "Install HAproxy in bastion host"
  package:
    name: haproxy
    state: present
    enabled: yes

- name: "Start HAproxy Service"
  service:
    name: haproxy
    state: start
    enabled: yes

- name: "Copy HAproxy configuration file from template"
  copy:
    src: ../vars/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
